# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gmail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import smtplib
from email.message import EmailMessage
import os
import cv2

class Ui_MainWindow(object):
    def mail(self):
        a=self.lineEdit.displayText()
        b=self.lineEdit_2.displayText()
        c=self.lineEdit_3.displayText()
        
        import sqlite3
                     
        db=sqlite3.connect("gmail.db")
        cursor=db.cursor()        
        command=''' update  gmail_table set name=?,password=?,receive=? '''
        print("aa")
        
        val=(a,b,c)  
        print("bb")             
        result=cursor.execute(command,val)          
        db.commit()       
        db.close
        print("done")
#########################################################################################

        sqliteConnection = sqlite3.connect('gmail.db')
        cursor = sqliteConnection.cursor()              
        sqlite_select_query = """SELECT * from gmail_table"""
        cursor.execute(sqlite_select_query)
        records = cursor.fetchall() 
        x=records[0][0]
        y=records[0][1]
        z=records[0][2]
        cursor.close()

#########################################################################################
        
        msg= EmailMessage()
        
        my_address = str(x)   #sender address
        
        app_generated_password = str(y)   # gmail generated password
        
        msg["Subject"] ="The Email Subject"   #email subject 
        
        msg["From"]= my_address      #sender address
        
        msg["To"] = str(z)     #reciver address
        
        with open('a.txt', 'r') as G:   
        
            msg.set_content(G.read())   #message body
        
            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
                
                smtp.login(my_address,app_generated_password)    #login gmail account
                
                print("sending mail")
                smtp.send_message(msg)   #send message 
                print("mail has sent")
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 110, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 160, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(430, 140, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 220, 111, 41))
        self.pushButton.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.mail)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Gmail"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Sender address"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Sender password"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Receiver address"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.label_3.setText(_translate("MainWindow", "From"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.label_4.setText(_translate("MainWindow", "Email"))
        self.label_5.setText(_translate("MainWindow", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
